const HKJC="https://racing.hkjc.com",CARD=HKJC+"/zh-hk/local/information/racecard",MODEL="V2.1-auto";
const HEADERS={"user-agent":"DragonResearch/2.1","accept-language":"zh-HK,zh;q=0.9"};
const HISTORY=[
 {date:"2026-09-09",venue:"跑馬地 A欄",kind:"正式核對",note:"第二版賽前研究排序；未加入T−3市場訊號。",summary:"首選入三甲4/8・全部候選11/23・8/8場至少中一匹",races:[
 [1,"三甲：12・11・5",[[6,"果然僥倖","三甲外"],[5,"金風萬里","第3"],[12,"添喜運","第1"]]],[2,"三甲：1・7・10",[[9,"準希望","三甲外"],[1,"勁進駒","第1"],[3,"紅海勁","三甲外"]]],[3,"三甲：6・1・11",[[1,"翠湖烈風","第2"],[3,"猛將兄","三甲外"],[4,"銀亮濠俠","三甲外"]]],[4,"三甲：10・4・6",[[2,"深心星","三甲外"],[10,"凝妙星","第1"]]],[5,"三甲：10・9・3",[[4,"做好自己","三甲外"],[5,"紫辰之星","三甲外"],[10,"將義","第1"]]],[6,"三甲：6・3・5",[[6,"福進","第1"],[2,"美麗登場","三甲外"],[8,"天火同人","三甲外"]]],[7,"三甲：1・2・12",[[1,"官金騏","第1"],[2,"博愛先鋒","第2"],[11,"比特星","三甲外"]]],[8,"三甲：11・4・1",[[11,"長勝隊長","第1"],[3,"馬達","三甲外"],[1,"志滿同行","第3"]]]]},
 {date:"2026-09-06",venue:"沙田",kind:"重建紀錄",note:"R1–R8有市場快照，但選擇係賽後按統一規則重建；R9–R10冇T−3快照。完整三甲名次未全部保存。",summary:"5/8入三甲・8場有重建選擇・唔計入第二版命中率",races:[
 [1,"13 同有運：第1",[[13,"同有運","第1"]]],[2,"1 駿馬之曲：第1",[[1,"駿馬之曲","第1"]]],[3,"3 錶之星河：四甲外／完整名次未保存",[[3,"錶之星河","三甲外"]]],[4,"10 志醒大將：第1",[[10,"志醒大將","第1"]]],[5,"7 光年程祥：第1",[[7,"光年程祥","第1"]]],[6,"14 金多囍：第4",[[14,"金多囍","第4"]]],[7,"8 飛鷹翱翔：四甲外／完整名次未保存",[[8,"飛鷹翱翔","三甲外"]]],[8,"2 八仟好運：第2",[[2,"八仟好運","第2"]]],[9,"冇T−3快照",[]],[10,"冇T−3快照",[]]]}
];
function plain(h){return h.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/&#(\d+);/g,function(_,n){return String.fromCharCode(+n)}).replace(/\s+/g," ").trim()}
function section(h,a,b){const x=h.indexOf(a);if(x<0)return"";const y=h.indexOf(b,x+a.length);return h.slice(x,y<0?undefined:y)}
function cells(r){return Array.from(r.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)).map(function(m){return plain(m[1])})}
async function get(url){const c=new AbortController(),t=setTimeout(function(){c.abort()},22000);try{const r=await fetch(url,{headers:HEADERS,redirect:"follow",signal:c.signal});if(!r.ok)throw Error("HKJC "+r.status);return{html:await r.text(),url:r.url}}finally{clearTimeout(t)}}
function parseCard(html,work){const info=plain(section(html,'<div class="f_fs13" style="line-height: 20px;">','</div>')),raceNo=+(info.match(/第\s*(\d+)\s*場/)?.[1]||0),raceTime=info.match(/(\d{1,2}:\d{2})/)?.[1]||"—",distance=info.match(/(\d{3,4}米)/)?.[1]||"資料不足",className=info.match(/第[一二三四五六七八九十]+班/)?.[0]||"級別待核",table=section(html,'id="racecardlist"','</table>\r\n        </div>'),rows=Array.from(table.matchAll(/<tr class="f_tac f_fs13">([\s\S]*?)<\/tr>/gi)).map(function(m){return cells(m[1])}).filter(function(c){return /^\d+$/.test(c[0]||"")&&c.length>=13}),horses=rows.map(function(c){return{horseNo:+c[0],form:(c[1]||"").split("/").map(Number).filter(function(n){return n>0&&n<99}),horseName:c[3],weight:+c[5]||0,draw:+c[8]||0,rating:+c[11]||0,delta:+c[12]||0,work:work.includes(">"+c[3]+"<")}});return{raceNo,raceTime,distance,className,horses}}
function pts(n){return({1:30,2:24,3:19,4:13,5:9,6:5}[n]||0)}
function score(d,venue){const distance=+d.distance.replace(/\D/g,""),valid=d.horses.filter(function(h){return h.form.length>=3&&h.draw&&h.rating&&h.weight}),rs=valid.map(function(h){return h.rating}),ws=valid.map(function(h){return h.weight}),minR=Math.min.apply(null,rs),maxR=Math.max.apply(null,rs),minW=Math.min.apply(null,ws),maxW=Math.max.apply(null,ws);const list=valid.map(function(h){const f=h.form.slice(0,6),den=f.reduce(function(s,_,i){return s+6-i},0),form=f.reduce(function(s,n,i){return s+pts(n)*(6-i)},0)/den,rating=maxR===minR?7.5:(h.rating-minR)/(maxR-minR)*15,weight=maxW===minW?5:(maxW-h.weight)/(maxW-minW)*10,inside=Math.max(0,1-(h.draw-1)/Math.max(1,valid.length-1)),draw=(venue==="HV"||distance<=1400?inside*15:7.5),momentum=Math.max(0,Math.min(10,5+h.delta)),coverage=(f.length>=6?55:45)+(h.work?10:0)+35;return{horseNo:h.horseNo,horseName:h.horseName,score:Math.round((form/30*50+rating+weight+draw+momentum)*10)/10,confidence:coverage>=90?"中高":coverage>=80?"中等":"較低",reasons:[f.slice(0,3).some(function(n){return n<=3})?"近期有入位":"近期表現一般",h.draw<=Math.ceil(valid.length/2)?"檔位相對有利":"外檔需蝕位風險",h.delta>0?"評分走勢向上":"評分未見上升",h.work?"晨操／試閘紀錄已讀取":"晨操資料未完整"],coverage}}).sort(function(a,b){return b.score-a.score||a.horseNo-b.horseNo}),coverage=list.length?Math.round(list.reduce(function(s,h){return s+h.coverage},0)/list.length):0;return{raceNo:d.raceNo,raceTime:d.raceTime,distance:d.distance,className:d.className,pace:"未有可靠跑法資料，不加分",coverage,picks:coverage>=75?list.slice(0,3):[]}}
async function sync(env){const first=await get(CARD),nav=first.html.match(/\?racedate=(\d{4}\/\d{2}\/\d{2})&Racecourse=(ST|HV)&RaceNo=2/i),info=plain(section(first.html,'<div class="f_fs13" style="line-height: 20px;">','</div>')),bits=info.match(/(\d{4})年(\d{1,2})月(\d{1,2})日/),date=(nav?.[1]||bits?.slice(1).map(function(x,i){return i?x.padStart(2,"0"):x}).join("/")||"").replaceAll("/","-"),venue=nav?.[2]||(/跑馬地/.test(info)?"HV":"ST"),count=Math.max.apply(null,[1].concat(Array.from(first.html.matchAll(/RaceNo=(\d+)/gi)).map(function(m){return+m[1]})));if(!date)throw Error("未能核實下一個賽日");const old=await env.DB.prepare("SELECT payload FROM meeting_snapshots WHERE meeting_date=? AND venue=? AND model_version=? AND locked=1").bind(date,venue,MODEL).first();if(old)return JSON.parse(old.payload);const races=[];for(let i=1;i<=count;i+=3){const batch=await Promise.all(Array.from({length:Math.min(3,count-i+1)},function(_,j){return i+j}).map(async function(n){const q="?racedate="+date.replaceAll("-","/")+"&Racecourse="+venue+"&RaceNo="+n,[card,work]=await Promise.all([n===1?Promise.resolve(first):get(CARD+q),get(HKJC+"/zh-hk/local/information/localtrackwork"+q)]);return score(parseCard(card.html,work.html),venue)}));races.push.apply(races,batch)}const payload={date,venue:venue==="HV"?"跑馬地":"沙田",venueCode:venue,modelVersion:MODEL,sourceCutoff:new Date().toISOString(),races};await env.DB.prepare("INSERT OR IGNORE INTO meeting_snapshots(meeting_date,venue,model_version,captured_at,source_url,payload,locked) VALUES(?,?,?,?,?,?,1)").bind(date,venue,MODEL,new Date().toISOString(),first.url,JSON.stringify(payload)).run();return payload}
const styles="*{box-sizing:border-box}body{margin:0;background:#071019;color:#edf3f7;font:16px system-ui,-apple-system,sans-serif}header{height:72px;border-bottom:1px solid #234;display:flex;align-items:center;justify-content:space-between;padding:0 max(18px,calc((100% - 1100px)/2))}.brand{font-weight:900;letter-spacing:.15em;color:#e4bd59}nav a{color:#9ab;text-decoration:none;margin-left:18px}.active{color:#e4bd59}main{max-width:1100px;margin:auto;padding:35px 18px}h1{font-size:36px;margin:0 0 8px}.sub{color:#8fa3b4}.notice{border:1px solid #675625;background:#201d12;padding:14px;border-radius:8px;margin:20px 0}.grid{display:grid;gap:12px}.races{grid-template-columns:1fr 1fr}.card{background:#0d1924;border:1px solid #223442;border-radius:10px;padding:17px}.racehead{display:flex;justify-content:space-between;border-bottom:1px solid #234;padding-bottom:10px;margin-bottom:8px}.racehead b,.summary{color:#e4bd59}.pick{display:grid;grid-template-columns:34px 1fr auto;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid #182b38}.num{display:grid;place-items:center;width:30px;height:30px;background:#20394a;color:#f3d070;border-radius:5px}.reason{font-size:13px;color:#91a5b2}.hit{color:#62d5aa}.miss{color:#8295a1}.tag{font-size:12px;color:#071019;background:#d4a93c;border-radius:4px;padding:4px 7px}.day{margin:28px 0}@media(max-width:720px){.races{grid-template-columns:1fr}h1{font-size:29px}header{padding:0 14px}}";
function shell(active,body){return'<!doctype html><html lang="zh-HK"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dragon 賽馬預測</title><style>'+styles+'</style><header><div class="brand">龍 DRAGON</div><nav><a class="'+(active==="latest"?"active":"")+'" href="/">最新預測</a><a class="'+(active==="history"?"active":"")+'" href="/history">歷史核對</a></nav></header><main>'+body+'</main></html>'}
function latest(){return shell("latest",'<h1>最近賽日預測</h1><p class="sub">每場最多3匹・固定模型・首次完整輸出後鎖定</p><div id="status" class="notice">正在讀取HKJC官方資料…</div><div id="races" class="grid races"></div><script>fetch("/api/sync",{method:"POST"}).then(function(r){return r.json()}).then(function(d){if(d.error)throw Error(d.error);status.textContent=d.date+"・"+d.venue+"｜"+d.modelVersion+"｜資料截止 "+d.sourceCutoff;races.innerHTML=d.races.map(function(r){return "<section class=card><div class=racehead><b>R"+r.raceNo+"　"+r.distance+"・"+r.className+"</b><span>"+r.raceTime+"</span></div>"+(r.picks.length?r.picks.map(function(p,i){return "<div class=pick><span class=num>"+p.horseNo+"</span><div><b>"+(i+1)+". "+p.horseName+"</b><div class=reason>"+p.reasons.join("・")+"</div></div><span class=tag>"+p.score+"</span></div>"}).join(""):"<p class=sub>資料覆蓋 "+r.coverage+"%，今場不選。</p>")+"</section>"}).join("")}).catch(function(e){status.textContent="更新失敗："+e.message+"。不會用舊資料冒充最新預測。"})</script>')}
function history(){let body='<h1>歷史預測 × 賽果</h1><p class="sub">只核對當時保存嘅選擇；重建資料另行標示</p>';HISTORY.forEach(function(d){body+='<section class=day><h2>'+d.date+'・'+d.venue+' <span class=tag>'+d.kind+'</span></h2><p class=sub>'+d.note+'</p><p class=summary>'+d.summary+'</p><div class="grid races">';d.races.forEach(function(r){body+='<div class=card><div class=racehead><b>R'+r[0]+'</b><span>'+r[1]+'</span></div>';if(r[2].length)r[2].forEach(function(p,i){body+='<div class=pick><span class=num>'+p[0]+'</span><b>'+(i+1)+'. '+p[1]+'</b><span class="'+(/^第[123]$/.test(p[2])?"hit":"miss")+'">'+p[2]+'</span></div>'});else body+='<p class=sub>冇T−3資料，冇產生重建選擇。</p>';body+='</div>'});body+='</div></section>'});return shell("history",body)}
export default{async fetch(req,env){const u=new URL(req.url);try{if(u.pathname==="/api/sync"&&req.method==="POST")return Response.json(await sync(env),{headers:{"cache-control":"no-store"}});if(u.pathname==="/history")return new Response(history(),{headers:{"content-type":"text/html;charset=utf-8"}});return new Response(latest(),{headers:{"content-type":"text/html;charset=utf-8"}})}catch(e){return Response.json({error:e.message||"系統錯誤"},{status:500})}},async scheduled(_,env){await sync(env)}};
