const assert=require('node:assert/strict');
const Bias=require('./track-bias.js');
const event={version:1,date:'2026-10-04',venue:'ST',rail:'A',family:'turn1200_1800',direction:'inside',pace:'unknown',confidence:'low',from:2,until:11,kind:'observe',evidence:[1],note:'R1',created_at:'2026-10-04T05:00:00Z'};
const tip={date:event.date,race:2,status:'ready',legs_status:'ready',freeze:'2026-10-04T13:30:00+08:00',received_at:'2026-10-04T13:29:50+08:00',banker:1,legs:[4,5,6,7],leg_scores:Object.fromEntries(Array.from({length:9},(_,i)=>[i+1,1-(i+1)/10])),runner_rows:Array.from({length:9},(_,i)=>[String(i+1),'','',String(i+1)])};
const context={status:'ready',date:event.date,race:2,venue:'ST',track:'TURF',rail:'A',distance:1400,prepared_at:'2026-10-04T12:00:00+08:00'};
let checks=0;
function test(fn){fn();checks++;}
test(()=>assert.equal(Bias.validate(event),event));
test(()=>assert.throws(()=>Bias.validate({...event,evidence:[2]})));
test(()=>assert.throws(()=>Bias.validate({...event,confidence:'high'})));
test(()=>assert.throws(()=>Bias.validate({...event,kind:'watering'})));
test(()=>assert.throws(()=>Bias.validate({...event,evidence:[]})));
test(()=>assert.throws(()=>Bias.validate({...event,until:1})));
test(()=>assert.throws(()=>Bias.validate({...event,created_at:'broken'})));
test(()=>assert.throws(()=>Bias.validate({...event,note:'x'.repeat(301)})));
test(()=>assert.equal(Bias.active([event],tip,context),event));
test(()=>assert.equal(Bias.active([{...event,created_at:'2026-10-04T06:00:00Z'}],tip,context),null));
test(()=>assert.equal(Bias.active([event],tip,{...context,rail:'B'}),null));
test(()=>assert.equal(Bias.active([event],tip,{...context,venue:'HV'}),null));
test(()=>assert.equal(Bias.active([event],tip,{...context,track:'AWT'}),null));
test(()=>assert.equal(Bias.active([event],tip,{...context,distance:1000}),null));
test(()=>assert.equal(Bias.active([event],tip,{...context,prepared_at:'2026-10-04T14:00:00+08:00'}),null));
test(()=>assert.equal(Bias.active([event],tip,{...context,race:3}),null));
test(()=>assert.equal(Bias.active([event],{...tip,received_at:'2026-10-04T13:31:00+08:00'},context),null));
test(()=>{const saved=JSON.stringify(tip),out=Bias.preview(tip,event,context);assert.deepEqual(out.legs,[4,5,6,2]);assert.equal(out.banker,1);assert.equal(JSON.stringify(tip),saved);});
test(()=>assert.equal(Bias.preview(tip,{...event,family:'straight1000'},context).changed,false));
test(()=>assert.equal(Bias.preview(tip,{...event,direction:'neutral'},context).changed,false));
test(()=>assert.equal(Bias.preview({...tip,legs_status:'unavailable'},event,context).changed,false));
test(()=>assert.equal(Bias.preview({...tip,runner_rows:[]},event,context).changed,false));
const reset={...event,direction:'unknown',pace:'unknown',kind:'watering',evidence:[],created_at:'2026-10-04T05:10:00Z'};
test(()=>{assert.equal(Bias.active([event,reset],tip,context),reset);assert.equal(Bias.preview(tip,reset,context).changed,false);});
test(()=>assert.equal(Bias.active([event,{...reset,until:2}],{...tip,race:3},{...context,race:3}),null));
test(()=>assert.equal(Bias.active([event,{...reset,from:3}],tip,context),event));
test(()=>{const fresh={...event,from:3,evidence:[2],created_at:'2026-10-04T05:20:00Z'};assert.equal(Bias.active([event,reset,fresh],{...tip,race:3},{...context,race:3}),fresh)});
test(()=>assert.equal(Bias.active([event,reset],tip,context),reset));
test(()=>assert.equal(Bias.preview(tip,{...event,direction:'outside'},context).added,8));
test(()=>{const storage={value:null,getItem(){return this.value},setItem(k,v){this.value=v}};Bias.save(storage,[],event);assert.equal(Bias.read(storage).length,1);storage.value='bad JSON';assert.deepEqual(Bias.read(storage),[])});
test(()=>assert.equal(Bias.matches(event,{...context,rail:'C'}),false));
test(()=>{const storage={setItem(){}};assert.throws(()=>Bias.save(storage,[event,reset],{...event,from:3,created_at:'2026-10-04T05:20:00Z'}));});
test(()=>assert.equal(Bias.active([event,reset,{...event,created_at:'2026-10-04T05:20:00Z'}],tip,context),reset));
console.log(`${checks} track-bias cutoff, reset, context and manual-preview checks passed`);
